<?php $_code = $this->getMethodCode() ?>

<?php
$cc_hash = $this->getCcHashFront();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($cc_hash): ?>
        <dl><!-- class="form-list" id="inspiregateway_saved">-->    
            <dt>    
                <input type="radio" value="yes" name="payment[use_saved]" <?php if($this->getInfoData('use_saved')=="yes") echo 'checked="checked"'; ?> onClick="jQuery('.cc_form').hide();"/>
                <label for="ig_saved">Use Saved Card</label>    
            </dt>    
            <dd style="position:relative;left:20px;">    
            <?php echo $cc_hash; ?>
        </dd>
        <dt>
            <input type="radio" value="no" name="payment[use_saved]" <?php if($this->getInfoData('use_saved')=="no") echo 'checked="checked"'; ?> onClick="jQuery('.cc_form').show();" checked/>
            <label for="ig_saved">Enter New Card</label>
        </dt>
        <dd style="position:relative;left:20px;">
            <?php else: ?>
                <input type="hidden" value="no" name="payment[use_saved]"/>
            <?php endif; ?>
                <div>    
                    <ul>    
                        <li>    
                            <div class="input-box cc_form">    
                                <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?> <span class="required">*</span></label><br />
                                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
                            </div>    
                        </li>    
                        <li>    
                            <div class="input-box cc_form">    
                                <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                                <?php $_ccType = $this->getInfoData('cc_type') ?>
                                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                                    <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                                <?php endforeach ?>
                                    </select>        
                                </div>        
                            </li>        
                            <li>        
                                <div class="input-box cc_form">        
                                    <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label><br />
                                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
                                </div>        
                            </li>        
                            <li>        
                                <div class="input-box cc_form">        
                                    <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br />
                                    <div class="v-fix">        
                                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month required-entry">
                                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                    <?php endforeach ?>
                                            </select>            
                                        </div>            
                                        <div class="v-fix cc_form">            
                                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                                                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                                                    <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                    <?php endforeach ?>
                                                    </select>                    
                                                </div>                    
                                            </div>                    
                                        </li>                    
                    <?php if ($this->hasVerification()): ?>
                                                            <li>                                        
                                                                <div class="input-box cc_form">                                        
                                                                    <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label><br />
                                                                    <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" /></div>
                                                                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                                                                </div>                                        
                                                            </li>                                        
                    <?php endif; ?>
                    <?php 
                    $method =  Mage::getSingleton('checkout/session')->getQuote()->getCheckoutMethod();
                    if($method!=Mage_Sales_Model_Quote::CHECKOUT_METHOD_GUEST):  /*display save card */

                      ?>
                    
                                                            <li>                                        
                                                                <div class="cc_form">                                        
                                                                    <input id="<?php echo $_code ?>_save_in_vault" type="checkbox" name="payment[save_in_vault]"  <?php if($this->getInfoData('save_in_vault')) echo 'checked="checked"'; ?> value="1" title="<?php echo $this->__('Save Credit Card') ?>"/>
                                                                    <label for="<?php echo $_code ?>_save_in_vault">
                                <?php echo $this->__('Save Credit Card') ?>
                                                        </label>                            
                                                    </div>                            
                                                </li>                            
                                                
                                                <?php endif;  /* display save_card box */ ?>
                                                
                                                            </ul>                                            
                                                        </div>                                            
                    <?php if ($cc_hash): ?>
                                                                </dd>                                            
                                                            </dl>                                                        
    <?php endif; ?>
</ul>
